name: azure-deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY_NAME: avaresfbacr
  CONTAINER_APP_NAME: focalboard
  RESOURCE_GROUP: dev_team
  PACKAGE_PATH: '.'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to ACR
      id: acr-creds
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./
        file: docker/Dockerfile
        push: true
        build-args: |
          SKIP_TESTS=true
          DB_TYPE=postgres
        tags: ${{ env.REGISTRY_NAME }}.azurecr.io/focalboard:${{ github.sha }}

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Create Storage Account
      id: storage-account
      run: |
        STORAGE_EXISTS=$(az storage account show --name avaresfbstorage --resource-group ${{ env.RESOURCE_GROUP }} --query "name" --output tsv 2>/dev/null || echo "")
        
        if [ -z "$STORAGE_EXISTS" ]; then
          echo "Creating storage account..."
          az storage account create \
            --name avaresfbstorage \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --location eastus \
            --sku Standard_LRS
        else
          echo "Storage account already exists."
        fi
        
        # Get storage key
        STORAGE_KEY=$(az storage account keys list --account-name avaresfbstorage --resource-group ${{ env.RESOURCE_GROUP }} --query "[0].value" -o tsv)
        echo "::set-output name=storage_key::$STORAGE_KEY"
    
    - name: Create File Share
      run: |
        STORAGE_KEY=$(az storage account keys list --account-name avaresfbstorage --resource-group ${{ env.RESOURCE_GROUP }} --query "[0].value" -o tsv)
        
        SHARE_EXISTS=$(az storage share exists --name focalboard-data --account-name avaresfbstorage --account-key "$STORAGE_KEY" --query "exists" -o tsv)
        
        if [ "$SHARE_EXISTS" = "false" ]; then
          echo "Creating Azure Files share..."
          az storage share create \
            --name focalboard-data \
            --account-name avaresfbstorage \
            --account-key "$STORAGE_KEY"
        else
          echo "File share already exists."
        fi

    - name: Create Container App Environment
      run: |
        ENV_EXISTS=$(az containerapp env show --name focalboard-env --resource-group ${{ env.RESOURCE_GROUP }} --query "name" --output tsv 2>/dev/null || echo "")
        
        if [ -z "$ENV_EXISTS" ]; then
          echo "Creating Container App Environment..."
          az containerapp env create \
            --name focalboard-env \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --location eastus
        else
          echo "Container App Environment already exists."
        fi
        
        # Get storage key
        STORAGE_KEY=$(az storage account keys list --account-name avaresfbstorage --resource-group ${{ env.RESOURCE_GROUP }} --query "[0].value" -o tsv)
        echo "::set-output name=storage_key::$STORAGE_KEY"

    - name: Add Storage to Container App Environment
      run: |
        # Get storage key again
        STORAGE_KEY=$(az storage account keys list --account-name avaresfbstorage --resource-group ${{ env.RESOURCE_GROUP }} --query "[0].value" -o tsv)
        
        # Add storage definition to Container App Environment
        echo "Adding Azure Files storage to Container App Environment..."
        az containerapp env storage set \
          --name focalboard-env \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --storage-name focalboard-data-storage \
          --storage-type AzureFile \
          --azure-file-account-name avaresfbstorage \
          --azure-file-account-key "$STORAGE_KEY" \
          --azure-file-share-name focalboard-data \
          --access-mode ReadWrite

    - name: Deploy to Container App
      run: |
        # Check if container app exists
        APP_EXISTS=$(az containerapp list --resource-group ${{ env.RESOURCE_GROUP }} --query "[?name=='${{ env.CONTAINER_APP_NAME }}'].name" -o tsv)
        
        if [ -z "$APP_EXISTS" ]; then
          echo "Creating new Container App..."
          az containerapp create \
            --name ${{ env.CONTAINER_APP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --environment focalboard-env \
            --registry-server "${{ env.REGISTRY_NAME }}.azurecr.io" \
            --registry-username "${{ steps.acr-creds.outputs.username }}" \
            --registry-password "${{ steps.acr-creds.outputs.password }}" \
            --image ${{ env.REGISTRY_NAME }}.azurecr.io/focalboard:${{ github.sha }} \
            --target-port 8000 \
            --ingress external \
            --env-vars "PORT=8000" "DB_TYPE=postgres" \
            --secrets "postgres-connection=${{ secrets.POSTGRES_CONNECTION_STRING }}" \
            --query properties.configuration.ingress.fqdn
        else
          echo "Updating existing Container App..."
          az containerapp update \
            --name ${{ env.CONTAINER_APP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --image ${{ env.REGISTRY_NAME }}.azurecr.io/focalboard:${{ github.sha }} \
            --env-vars "PORT=8000" "DB_TYPE=postgres" \
            --secrets "postgres-connection=${{ secrets.POSTGRES_CONNECTION_STRING }}"
        fi
        
        echo "Configuring volume mounts using YAML approach..."
        
        # Export the container app configuration to YAML
        echo "Ensuring jq and PyYAML are installed for YAML/JSON processing..."
        if ! command -v jq &> /dev/null; then
          echo "Installing jq..."
          apt-get update && apt-get install -y jq
        else
          echo "jq is already installed"
        fi
        
        echo "Installing PyYAML for YAML<->JSON conversion..."
        pip install pyyaml
        
        echo "Exporting current Container App configuration to YAML..."
        az containerapp show \
          --name ${{ env.CONTAINER_APP_NAME }} \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --output yaml > app_config.yaml
        
        # Create a backup of the original configuration
        cp app_config.yaml app_config_original.yaml
        
        # Use a simpler approach with cat to create volume configuration files
        echo "Creating volume configuration files..."
        
        # Create separate patch files for volumes and volume mounts
        # We'll use Python to apply these patches without overwriting existing config
        
        # Create volume definition patch
        cat > volume_def.yaml << 'EOVOL'
        name: focalboard-data-volume
        storageType: AzureFile
        storageName: focalboard-data-storage
        EOVOL
        
        # Create volume mount patch
        cat > volume_mount.yaml << 'EOMOUNT'
        volumeName: focalboard-data-volume
        mountPath: "/opt/focalboard/data"
        EOMOUNT
        
        # Show the volume configuration to be applied
        echo "Volume definition to be applied:"
        cat volume_def.yaml
        echo "Volume mount to be applied:"
        cat volume_mount.yaml
        
        echo "Applying patches with Python..."
        
        # Create a Python script to apply patches without overriding existing properties
        cat > apply_patches.py << 'EOPY'
        import json
        import yaml
        import sys
        
        # Load the original app configuration
        with open('app_config.yaml', 'r') as f:
            config = yaml.safe_load(f)
        
        # Load the volume definition
        with open('volume_def.yaml', 'r') as f:
            volume_def = yaml.safe_load(f)
        
        # Load the volume mount
        with open('volume_mount.yaml', 'r') as f:
            volume_mount = yaml.safe_load(f)
        
        # Initialize volumes list if it doesn't exist
        if 'properties' not in config:
            config['properties'] = {}
        if 'template' not in config['properties']:
            config['properties']['template'] = {}
        if 'volumes' not in config['properties']['template'] or config['properties']['template']['volumes'] is None:
            config['properties']['template']['volumes'] = []
        
        # Check if volume already exists before adding
        volume_exists = False
        for vol in config['properties']['template']['volumes']:
            if vol.get('name') == volume_def.get('name'):
                volume_exists = True
                print(f"Volume {volume_def.get('name')} already exists, skipping addition")
                break
                
        # Add the volume definition only if it doesn't already exist
        if not volume_exists:
            print(f"Adding volume {volume_def.get('name')}")
            config['properties']['template']['volumes'].append(volume_def)
        
        # Find the container named 'focalboard' and add volume mount if not already present
        if 'containers' in config['properties']['template']:
            for container in config['properties']['template']['containers']:
                if container.get('name') == 'focalboard':
                    if 'volumeMounts' not in container or container['volumeMounts'] is None:
                        container['volumeMounts'] = []
                    
                    # Check if volume mount already exists
                    mount_exists = False
                    for mount in container['volumeMounts']:
                        if (mount.get('volumeName') == volume_mount.get('volumeName') and 
                            mount.get('mountPath') == volume_mount.get('mountPath')):
                            mount_exists = True
                            print(f"Volume mount {volume_mount.get('volumeName')} already exists, skipping addition")
                            break
                    
                    # Add mount only if it doesn't exist
                    if not mount_exists:
                        print(f"Adding volume mount {volume_mount.get('volumeName')} to container {container.get('name')}")
                        container['volumeMounts'].append(volume_mount)
                    break
        
        # Write the updated configuration
        with open('updated_config.yaml', 'w') as f:
            yaml.dump(config, f)
        EOPY
        
        # Execute the Python script to apply patches
        python apply_patches.py
        
        # Show the changes
        echo "Showing diff between original and updated config:"
        diff app_config.yaml updated_config.yaml || true
        
        # Update the container app with the new configuration
        echo "Updating Container App with volume configuration..."
        az containerapp update \
          --name ${{ env.CONTAINER_APP_NAME }} \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --yaml updated_config.yaml

    - name: Get Container App URL
      id: app-url
      run: |
        APP_URL=$(az containerapp show --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --query properties.configuration.ingress.fqdn -o tsv)
        echo "::set-output name=url::https://$APP_URL"
        echo "Focalboard is now deployed at: https://$APP_URL"
